= Flask App Using Neo4j Database

I completed this tutorial from the Neo4j GraphAcademy. I learned how to create an API interacting with a Neo4j graph database using the query language Cypher. I created routes for HTTP requests that retrieved 'movie,' 'people' and 'user' nodes, and filtered them by attributes and relationships. I also created routes for posting and deleting users to the database. Graph databases are better suited than relational databases in some contexts such as anaylyzing network topology. For information about how to do this tutorial yourself, see below.

= Building Neo4j Applications with Python

> Learn how to interact with Neo4j from Python using the Neo4j Python Driver

This repository accompanies the link:https://graphacademy.neo4j.com/courses/app-python/[Building Neo4j Applications with Python course^] on link:https://graphacademy.neo4j.com/[Neo4j GraphAcademy^].

For a complete walkthrough of this repository,  link:https://graphacademy.neo4j.com/courses/app-python/[enroll now^].

== A Note on comments

You may spot a number of comments in this repository that look a little like this:

[source,python]
----
# tag::something[]
someCode()
# end::something[]
----


We use link:https://asciidoc-py.github.io/index.html[Asciidoc^] to author our courses.
Using these tags means that we can use a macro to include portions of code directly into the course itself.

From the point of view of the course, you can go ahead and ignore them.


== Setting up your evironment

[source,sh]
----
python -m venv neoflix

source neoflix/bin/activate
----



== Running the Application

[source,sh]
export FLASK_APP=api
export FLASK_ENV=development
flask run

